### ISSUE TITLE
feat: add link to VLprojects/webrtc-issue-detector utility

### ISSUE THREAD

**Issue by evgmel** [webrtcwork/webrtcwork#36]
Hello!
I would like to suggest adding link to this utility https://github.com/VLprojects/webrtc-issue-detector 
that helps to detect WebRTC issues and calculate MOS for existing PeerConnections.
I guess it could be useful for the community.

**Comment by evgmel** [comment]
@Sean-Der Would you tell me please who could help adding the link to the existing list of helpful WebRTC utils
https://github.com/VLprojects/webrtc-issue-detector ?

**Comment by notedit** [comment]
Pull  request  please

**Comment by evgmel** [comment]
@notedit Thank you for the reply! 
It's the [PR link](https://github.com/webrtcwork/webrtcwork/pull/38)
